/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ExtendedCmp {
        "method1": () => Promise<void>;
        "method2": () => Promise<void>;
        /**
          * @default 'ExtendedCmp text'
         */
        "prop1": string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2": string;
    }
    interface ExtendedCmpCmp {
        "method1": () => Promise<void>;
        "method2": () => Promise<void>;
        /**
          * @default 'ExtendedCmp text'
         */
        "prop1": string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2": string;
    }
    interface ExtendsAbstract {
        "method1": () => Promise<void>;
        "method2": () => Promise<void>;
        /**
          * @default 'default text'
         */
        "prop1": string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2": string;
    }
    interface ExtendsCmpCmp {
        "method1": () => Promise<void>;
        "method2": () => Promise<void>;
        /**
          * @default 'default text'
         */
        "prop1": string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2": string;
    }
    interface ExtendsControllerUpdates {
    }
    interface ExtendsDirectState {
    }
    interface ExtendsExternal {
        "method1": () => Promise<void>;
        "method2": () => Promise<void>;
        /**
          * @default 'default text'
         */
        "prop1": string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2": string;
    }
    interface ExtendsLifecycleBasic {
    }
    interface ExtendsLifecycleMultilevel {
    }
    interface ExtendsMethods {
        /**
          * Base method that can be called by child components
         */
        "baseMethod": () => Promise<string>;
        /**
          * Child-specific method that uses parent's protected helper
         */
        "childMethod": () => Promise<string>;
        /**
          * Method that composes parent and child behavior
         */
        "composedMethod": () => Promise<string>;
        /**
          * Method to get the call log for testing
         */
        "getCallLog": () => Promise<string[]>;
        /**
          * Method to get internal value for testing
         */
        "getInternalValue": () => Promise<string>;
        /**
          * Override parent method with super() call
         */
        "overridableMethod": () => Promise<string>;
        /**
          * Method to reset state for testing
         */
        "reset": () => Promise<void>;
        /**
          * Method to trigger display update from test
         */
        "updateDisplay": (value: string) => Promise<void>;
    }
    interface ExtendsMixinCmp {
        "method1": () => Promise<void>;
        "method2": () => Promise<void>;
        "method3": () => Promise<void>;
        /**
          * @default 'default text'
         */
        "prop1": string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2": string;
        /**
          * @default 'mixin b text'
         */
        "prop3": string;
    }
    /**
     * Test Case #3: Property & State Inheritance Basics
     * This component extends PropsStateBase to test:
     * -
     * @Prop inheritance from base class
     * -
     * @State inheritance from base class
     * - Additional
     * @Prop and
     * @State without conflicts
     * - Property reactivity (inherited props/state trigger re-renders)
     */
    interface ExtendsPropsState {
        /**
          * @default 0
         */
        "baseCount": number;
        /**
          * @default 'base prop value'
         */
        "baseProp": string;
        /**
          * @default 'component prop value'
         */
        "componentProp": string;
        "incrementBaseCount": () => Promise<void>;
        "toggleBaseEnabled": () => Promise<void>;
        "updateBaseState": (value: string) => Promise<void>;
        "updateComponentState": (value: string) => Promise<void>;
    }
    interface TsTargetProps {
        /**
          * @default 'basicProp'
         */
        "basicProp": string;
        "decoratedGetterSetterProp": number;
        /**
          * @default -10
         */
        "decoratedProp": number;
        "dynamicLifecycle": string[];
    }
}
declare global {
    interface HTMLExtendedCmpElement extends Components.ExtendedCmp, HTMLStencilElement {
    }
    var HTMLExtendedCmpElement: {
        prototype: HTMLExtendedCmpElement;
        new (): HTMLExtendedCmpElement;
    };
    interface HTMLExtendedCmpCmpElement extends Components.ExtendedCmpCmp, HTMLStencilElement {
    }
    var HTMLExtendedCmpCmpElement: {
        prototype: HTMLExtendedCmpCmpElement;
        new (): HTMLExtendedCmpCmpElement;
    };
    interface HTMLExtendsAbstractElement extends Components.ExtendsAbstract, HTMLStencilElement {
    }
    var HTMLExtendsAbstractElement: {
        prototype: HTMLExtendsAbstractElement;
        new (): HTMLExtendsAbstractElement;
    };
    interface HTMLExtendsCmpCmpElement extends Components.ExtendsCmpCmp, HTMLStencilElement {
    }
    var HTMLExtendsCmpCmpElement: {
        prototype: HTMLExtendsCmpCmpElement;
        new (): HTMLExtendsCmpCmpElement;
    };
    interface HTMLExtendsControllerUpdatesElement extends Components.ExtendsControllerUpdates, HTMLStencilElement {
    }
    var HTMLExtendsControllerUpdatesElement: {
        prototype: HTMLExtendsControllerUpdatesElement;
        new (): HTMLExtendsControllerUpdatesElement;
    };
    interface HTMLExtendsDirectStateElement extends Components.ExtendsDirectState, HTMLStencilElement {
    }
    var HTMLExtendsDirectStateElement: {
        prototype: HTMLExtendsDirectStateElement;
        new (): HTMLExtendsDirectStateElement;
    };
    interface HTMLExtendsExternalElement extends Components.ExtendsExternal, HTMLStencilElement {
    }
    var HTMLExtendsExternalElement: {
        prototype: HTMLExtendsExternalElement;
        new (): HTMLExtendsExternalElement;
    };
    interface HTMLExtendsLifecycleBasicElement extends Components.ExtendsLifecycleBasic, HTMLStencilElement {
    }
    var HTMLExtendsLifecycleBasicElement: {
        prototype: HTMLExtendsLifecycleBasicElement;
        new (): HTMLExtendsLifecycleBasicElement;
    };
    interface HTMLExtendsLifecycleMultilevelElement extends Components.ExtendsLifecycleMultilevel, HTMLStencilElement {
    }
    var HTMLExtendsLifecycleMultilevelElement: {
        prototype: HTMLExtendsLifecycleMultilevelElement;
        new (): HTMLExtendsLifecycleMultilevelElement;
    };
    interface HTMLExtendsMethodsElement extends Components.ExtendsMethods, HTMLStencilElement {
    }
    var HTMLExtendsMethodsElement: {
        prototype: HTMLExtendsMethodsElement;
        new (): HTMLExtendsMethodsElement;
    };
    interface HTMLExtendsMixinCmpElement extends Components.ExtendsMixinCmp, HTMLStencilElement {
    }
    var HTMLExtendsMixinCmpElement: {
        prototype: HTMLExtendsMixinCmpElement;
        new (): HTMLExtendsMixinCmpElement;
    };
    /**
     * Test Case #3: Property & State Inheritance Basics
     * This component extends PropsStateBase to test:
     * -
     * @Prop inheritance from base class
     * -
     * @State inheritance from base class
     * - Additional
     * @Prop and
     * @State without conflicts
     * - Property reactivity (inherited props/state trigger re-renders)
     */
    interface HTMLExtendsPropsStateElement extends Components.ExtendsPropsState, HTMLStencilElement {
    }
    var HTMLExtendsPropsStateElement: {
        prototype: HTMLExtendsPropsStateElement;
        new (): HTMLExtendsPropsStateElement;
    };
    interface HTMLTsTargetPropsElement extends Components.TsTargetProps, HTMLStencilElement {
    }
    var HTMLTsTargetPropsElement: {
        prototype: HTMLTsTargetPropsElement;
        new (): HTMLTsTargetPropsElement;
    };
    interface HTMLElementTagNameMap {
        "extended-cmp": HTMLExtendedCmpElement;
        "extended-cmp-cmp": HTMLExtendedCmpCmpElement;
        "extends-abstract": HTMLExtendsAbstractElement;
        "extends-cmp-cmp": HTMLExtendsCmpCmpElement;
        "extends-controller-updates": HTMLExtendsControllerUpdatesElement;
        "extends-direct-state": HTMLExtendsDirectStateElement;
        "extends-external": HTMLExtendsExternalElement;
        "extends-lifecycle-basic": HTMLExtendsLifecycleBasicElement;
        "extends-lifecycle-multilevel": HTMLExtendsLifecycleMultilevelElement;
        "extends-methods": HTMLExtendsMethodsElement;
        "extends-mixin-cmp": HTMLExtendsMixinCmpElement;
        "extends-props-state": HTMLExtendsPropsStateElement;
        "ts-target-props": HTMLTsTargetPropsElement;
    }
}
declare namespace LocalJSX {
    interface ExtendedCmp {
        /**
          * @default 'ExtendedCmp text'
         */
        "prop1"?: string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2"?: string;
    }
    interface ExtendedCmpCmp {
        /**
          * @default 'ExtendedCmp text'
         */
        "prop1"?: string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2"?: string;
    }
    interface ExtendsAbstract {
        /**
          * @default 'default text'
         */
        "prop1"?: string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2"?: string;
    }
    interface ExtendsCmpCmp {
        /**
          * @default 'default text'
         */
        "prop1"?: string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2"?: string;
    }
    interface ExtendsControllerUpdates {
    }
    interface ExtendsDirectState {
    }
    interface ExtendsExternal {
        /**
          * @default 'default text'
         */
        "prop1"?: string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2"?: string;
    }
    interface ExtendsLifecycleBasic {
    }
    interface ExtendsLifecycleMultilevel {
    }
    interface ExtendsMethods {
    }
    interface ExtendsMixinCmp {
        /**
          * @default 'default text'
         */
        "prop1"?: string;
        /**
          * @default 'ExtendedCmp prop2 text'
         */
        "prop2"?: string;
        /**
          * @default 'mixin b text'
         */
        "prop3"?: string;
    }
    /**
     * Test Case #3: Property & State Inheritance Basics
     * This component extends PropsStateBase to test:
     * -
     * @Prop inheritance from base class
     * -
     * @State inheritance from base class
     * - Additional
     * @Prop and
     * @State without conflicts
     * - Property reactivity (inherited props/state trigger re-renders)
     */
    interface ExtendsPropsState {
        /**
          * @default 0
         */
        "baseCount"?: number;
        /**
          * @default 'base prop value'
         */
        "baseProp"?: string;
        /**
          * @default 'component prop value'
         */
        "componentProp"?: string;
    }
    interface TsTargetProps {
        /**
          * @default 'basicProp'
         */
        "basicProp"?: string;
        "decoratedGetterSetterProp"?: number;
        /**
          * @default -10
         */
        "decoratedProp"?: number;
        "dynamicLifecycle"?: string[];
    }
    interface IntrinsicElements {
        "extended-cmp": ExtendedCmp;
        "extended-cmp-cmp": ExtendedCmpCmp;
        "extends-abstract": ExtendsAbstract;
        "extends-cmp-cmp": ExtendsCmpCmp;
        "extends-controller-updates": ExtendsControllerUpdates;
        "extends-direct-state": ExtendsDirectState;
        "extends-external": ExtendsExternal;
        "extends-lifecycle-basic": ExtendsLifecycleBasic;
        "extends-lifecycle-multilevel": ExtendsLifecycleMultilevel;
        "extends-methods": ExtendsMethods;
        "extends-mixin-cmp": ExtendsMixinCmp;
        "extends-props-state": ExtendsPropsState;
        "ts-target-props": TsTargetProps;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "extended-cmp": LocalJSX.ExtendedCmp & JSXBase.HTMLAttributes<HTMLExtendedCmpElement>;
            "extended-cmp-cmp": LocalJSX.ExtendedCmpCmp & JSXBase.HTMLAttributes<HTMLExtendedCmpCmpElement>;
            "extends-abstract": LocalJSX.ExtendsAbstract & JSXBase.HTMLAttributes<HTMLExtendsAbstractElement>;
            "extends-cmp-cmp": LocalJSX.ExtendsCmpCmp & JSXBase.HTMLAttributes<HTMLExtendsCmpCmpElement>;
            "extends-controller-updates": LocalJSX.ExtendsControllerUpdates & JSXBase.HTMLAttributes<HTMLExtendsControllerUpdatesElement>;
            "extends-direct-state": LocalJSX.ExtendsDirectState & JSXBase.HTMLAttributes<HTMLExtendsDirectStateElement>;
            "extends-external": LocalJSX.ExtendsExternal & JSXBase.HTMLAttributes<HTMLExtendsExternalElement>;
            "extends-lifecycle-basic": LocalJSX.ExtendsLifecycleBasic & JSXBase.HTMLAttributes<HTMLExtendsLifecycleBasicElement>;
            "extends-lifecycle-multilevel": LocalJSX.ExtendsLifecycleMultilevel & JSXBase.HTMLAttributes<HTMLExtendsLifecycleMultilevelElement>;
            "extends-methods": LocalJSX.ExtendsMethods & JSXBase.HTMLAttributes<HTMLExtendsMethodsElement>;
            "extends-mixin-cmp": LocalJSX.ExtendsMixinCmp & JSXBase.HTMLAttributes<HTMLExtendsMixinCmpElement>;
            /**
             * Test Case #3: Property & State Inheritance Basics
             * This component extends PropsStateBase to test:
             * -
             * @Prop inheritance from base class
             * -
             * @State inheritance from base class
             * - Additional
             * @Prop and
             * @State without conflicts
             * - Property reactivity (inherited props/state trigger re-renders)
             */
            "extends-props-state": LocalJSX.ExtendsPropsState & JSXBase.HTMLAttributes<HTMLExtendsPropsStateElement>;
            "ts-target-props": LocalJSX.TsTargetProps & JSXBase.HTMLAttributes<HTMLTsTargetPropsElement>;
        }
    }
}
